### ISSUE TITLE
NoSuchMethod - NBTItemSerializer - 1.12

### ISSUE THREAD

**Issue by JamieSinn** [GeorgH93/Bukkit_Bungee_PluginLib#1]
`2017-06-08 16:40:08 [WARN] java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.ItemStack.createStack(net.minecraft.server.v1_12_R1.NBTTagCompound)
2017-06-08 16:40:08 [WARN] 	at java.lang.Class.getDeclaredMethod(Unknown Source)
2017-06-08 16:40:08 [WARN] 	at at.pcgamingfreaks.Reflection.getMethod(Reflection.java:130)
2017-06-08 16:40:08 [WARN] 	at at.pcgamingfreaks.Bukkit.ItemStackSerializer.NBTItemStackSerializer.<clinit>(NBTItemStackSerializer.java:46)`

**Comment by GeorgH93** [comment]
You are using a version of the library that is unaware of MC 1.12 please update it.
You can find the newest builds here: https://ci.pcgamingfreaks.at/job/PluginLib/

**Comment by JamieSinn** [comment]
It'd be helpful if you change the snapshot number between MC versions. Otherwise maven has problems.
